export const FILTER_FACULTY = 'FILTER_FACULTY';
export const FILTER_FACULTY_SUCCESS = 'FILTER_FACULTY_SUCCESS';

export const CLEAR_FILTER_FACULTY = 'CLEAR_FILTER_FACULTY';
export const CLEAR_FILTER_FACULTY_SUCCESS = 'CLEAR_FILTER_FACULTY_SUCCESS';
